### ISSUE TITLE
 Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropFilterOp only supports NHWC. [[{{node gradients/conv1d_grad/Conv2DBackpropFilter}}]]

### ISSUE THREAD

**Issue by MEARAZKI** [qq456cvb/KdNet-Tensorflow#2]
Thank you for sharing 
I'm a beginner ,
I try to run your code on my machine but I have this error
thank you 
*****************************************************
[1114 16:36:44 @base.py:241] Graph Finalized.
[1114 16:36:44 @inference_runner.py:95] [InferenceRunner] Will eval 78 iterations
[1114 16:36:45 @base.py:273] Start Epoch 1 ...
  0%|                                                                                                                                             |0/307[00:00<?,?it/s]2020-11-14 16:36:47.313909: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropFilterOp only supports NHWC.
         [[{{node gradients/conv1d_grad/Conv2DBackpropFilter}}]]
  0%|                                                                                                                                             |0/307[00:02<?,?it/s]
Traceback (most recent call last):
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilterOp only supports NHWC.
         [[{{node gradients/conv1d_grad/Conv2DBackpropFilter}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Phd\Documents\Projet\KdNet-Tensorflow-master\model.py", line 128, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\train\interface.py", line 99, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\train\base.py", line 342, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\train\base.py", line 314, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\utils\argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\train\base.py", line 279, in main_loop
    self.run_step()  # implemented by subclass
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorpack\train\base.py", line 179, in run_step
    self.hooked_sess.run(self.train_op)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\Phd\anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\Phd\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilterOp only supports NHWC.
         [[node gradients/conv1d_grad/Conv2DBackpropFilter (defined at \anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'gradients/conv1d_grad/Conv2DBackpropFilter':
  File "\Documents\Projet\KdNet-Tensorflow-master\model.py", line 128, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "\anaconda3\lib\site-packages\tensorpack\train\interface.py", line 89, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "\anaconda3\lib\site-packages\tensorpack\utils\argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorpack\train\tower.py", line 219, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "\anaconda3\lib\site-packages\tensorpack\train\trainers.py", line 49, in _setup_graph
    grads = self._make_get_grad_fn(input, get_cost_fn, get_opt_fn)()
  File "\anaconda3\lib\site-packages\tensorpack\train\tower.py", line 276, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "\anaconda3\lib\site-packages\tensorpack\train\tower.py", line 271, in compute_grad_from_inputs
    aggregation_method=self.AGGREGATION_METHOD)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 679, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 350, in _MaybeCompile
    return grad_fn()  # Exit early
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 679, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_grad.py", line 606, in _Conv2DGrad
    data_format=data_format)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1238, in conv2d_backprop_filter
    name=name)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'conv1d', defined at:
  File "\Documents\Projet\KdNet-Tensorflow-master\model.py", line 128, in <module>
    launch_train_with_config(config, SimpleTrainer())
[elided 4 identical lines from previous traceback]
  File "\anaconda3\lib\site-packages\tensorpack\train\tower.py", line 276, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "\anaconda3\lib\site-packages\tensorpack\train\tower.py", line 250, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "\anaconda3\lib\site-packages\tensorpack\tfutils\tower.py", line 291, in __call__
    output = self._tower_fn(*args)
  File "\Documents\Projet\KdNet-Tensorflow-master\model.py", line 38, in build_graph
    x = tf.transpose(tf.nn.conv1d(points, tf.get_variable('kernel_pre', [1, DIM, 32]), 1, 'SAME', data_format='NCHW'), (0, 2, 1))
  File "\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1681, in conv1d
    name=name)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by qq456cvb** [comment]
It seems that this is caused by API inconsistency of Conv2D in Tensorflow, could you try Tensorflow v1.13 or v1.14
